DROP TABLE Users;

CREATE TABLE Users (
    id INTEGER NOT NULL GENERATED ALWAYS AS IDENTITY (START WITH 1, INCREMENT BY 1),
    username VARCHAR(64) UNIQUE,
    password VARCHAR(512),
    name VARCHAR(128),
    email VARCHAR(256),
    date DATE NOT NULL WITH DEFAULT CURRENT DATE
);

